const months = {
  'en-US': [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],
  'ru-RU': [
    'январь',
    'февраль',
    'март',
    'апрель',
    'май',
    'июнь',
    'июль',
    'август',
    'сентябрь',
    'октябрь',
    'ноябрь',
    'декабрь',
  ],
  'pt-PT': [
    'Janeiro',
    'fevereiro',
    'março',
    'abril',
    'maio',
    'junho',
    'julho',
    'agosto',
    'setembro',
    'Outubro',
    'novembro',
    'dezembro',
  ],
  'es-ES': [
    'Enero',
    'Febrero',
    'Marzo',
    'Abril',
    'Mayo',
    'Junio',
    'Julio',
    'Agosto',
    'Septiembre',
    'Octubre',
    'Noviembre',
    'Diciembre',
  ],
  'bs-BA': [
    'Januar',
    'Februar',
    'Mart',
    'April',
    'Maj',
    'Juni',
    'Juli',
    'August',
    'September',
    'Oktobar',
    'Novembar',
    'Decembar',
  ],
  'sr-SP': [
    'januar',
    'februar',
    'mart',
    'april',
    'maj',
    'jun',
    'jul',
    'avgust',
    'septembar',
    'oktobar',
    'novembar',
    'decembar',
  ],
  'sr-ME': [
    'Januar',
    'Februar',
    'Mart',
    'April',
    'Maj',
    'Jun',
    'Jul',
    'Avgust',
    'Septembar',
    'Oktobar',
    'Novembar',
    'Decembar',
  ],
  'hr-HR': [
    'siječanj',
    'veljača',
    'ožujak',
    'travanj',
    'svibanj',
    'lipanj',
    'srpanj',
    'kolovoz',
    'rujan',
    'listopad',
    'studeni',
    'prosinac',
  ],
  'fr-FR': [
    'janvier',
    'février',
    'mars',
    'avril',
    'mai',
    'juin',
    'juillet',
    'août',
    'septembre',
    'octobre',
    'novembre',
    'décembre  ',
  ],
  'nl-NL': [
    'januari',
    'februari',
    'maart',
    'april',
    'mei',
    'juni',
    'juli',
    'augustus',
    'september',
    'oktober',
    'november',
    'december',
  ],
  'el-GR': [
    'Ιανουάριος',
    'Φεβρουάριος',
    'Μάρτιος',
    'Απρίλιος',
    'Μάιος',
    'Ιούνιος',
    'Ιούλιος',
    'Αύγουστος',
    'Σεπτέμβριος',
    'Οκτώβριος',
    'Νοέμβριος',
    'Δεκέμβριος',
  ],
  'si-SI': [
    'Januar',
    'Februar',
    'Marec',
    'April',
    'Maj',
    'Junij',
    'Julij',
    'Avgust',
    'September',
    'Oktober',
    'November',
    'December',
  ],
};
const weekdays = {
  'en-US': ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  'ru-RU': ['Вос', 'Пон', 'Вто', 'Сре', 'Чет', 'Пят', 'Суб'],
  'pt-PT': ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
  'es-ES': ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sá'],
  'bs-BA': ['Ne', 'Po', 'Ut', 'Sr', 'Če', 'Pe', 'Su'],
  'sr-SP': ['NED', 'PON', 'UTO', 'SRI', 'ČET', 'PET', 'SUB'],
  'sr-ME': ['Ne', 'Po', 'Ut', 'Sr', 'Če', 'Pe', 'Su'],
  'hr-HR': ['ned', 'pon', 'uto', 'sri', 'čet', 'pet', 'sub'],
  'fr-FR': ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
  'nl-NL': ['Zo', 'Ma', 'Di', 'Wo', 'Do', 'Vr', 'Za'],
  'el-GR': ['Κυρ', 'Δευ', 'ΤΡΙ', 'Τετ', 'ΠΕΜ', 'Παρ', 'ΣΑΒ'],
  'si-SI': ['Ned', 'Pon', 'Tor', 'Sre', 'Čet', 'Pet', 'Sob'],
};
const choose = str => {
  return {
    'zh-CN': {
      vanCalendar: {
        monthTitle: (year, month) => {
          return `${months[str][month - 1]} ${year}`;
        },
        weekdays: weekdays[str],
      },
    },
  };
};
export default choose;
